export const DICTS = {
  GET_CONT_TYPES_DICT: 'GET_CONT_TYPES_DICT',
  GET_GARBAGE_GEN_DICT: 'GET_GARBAGE_GEN_DICT',
  GET_NEW_GARBAGE_GEN_DICT: 'GET_NEW_GARBAGE_GEN_DICT',
  GET_POI_DICT: 'GET_POI_DICT',
  GET_NEW_POI_DICT: 'GET_NEW_POI_DICT',

  UPDATE_CREATED_GARBAGE_GEN: 'UPDATE_CREATED_GARBAGE_GEN',
  UPDATE_CREATED_POI_DICT: 'UPDATE_CREATED_POI_DICT'
};
