export const JOURNAL = {
  GET_JOURNAL_SUCCESS: 'GET_JOURNAL_SUCCESS',
  GET_JOURNAL_IS_LOADING: 'GET_JOURNAL_IS_LOADING',
  GET_JOURNAL_ERROR: 'GET_JOURNAL_ERROR',

  UPDATE_CONTAINER: 'UPDATE_CONTAINER',
  UPDATE_WAYPOINT: 'UPDATE_WAYPOINT',
  ADD_CONTAINER: 'ADD_CONTAINER',
  ADD_BULKY: 'ADD_BULKY',
  ADD_WAYPOINT: 'ADD_WAYPOINT',

  REMOVE_JOURNAL: 'REMOVE_JOURNAL'
};
